services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    networks:
      - etiketten-netzwerk
    volumes:
      - ./backend/app/.env:/app/.env:ro

  frontend:
    build:
      context: ./frontend
    env_file:
      - ./frontend/.env
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - etiketten-netzwerk

networks:
  etiketten-netzwerk:
    driver: bridge