services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    networks:
      - etiketten-netzwerk

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - etiketten-netzwerk

networks:
  etiketten-netzwerk:
    driver: bridge