services:
  backend:
    image: registry.cstrube.de/etiketten-app/backend:latest
    ports:
      - "8000:8000"
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - etiketten-netzwerk
    environment:
      - DOCKER_REGISTRY_USERNAME=${DOCKER_REGISTRY_USERNAME}
      - DOCKER_REGISTRY_PASSWORD=${DOCKER_REGISTRY_PASSWORD}
    volumes:
      - backend-data:/app
      - ./backend/app/.env:/app/.env:ro

  frontend:
    image: registry.cstrube.de/etiketten-app/frontend:latest
    env_file:
      - .env
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - etiketten-netzwerk
    environment:
      - DOCKER_REGISTRY_USERNAME=${DOCKER_REGISTRY_USERNAME}
      - DOCKER_REGISTRY_PASSWORD=${DOCKER_REGISTRY_PASSWORD}
    volumes:
      - ./frontend/.env:/app/.env:ro

networks:
  etiketten-netzwerk:
    driver: bridge

volumes:
  backend-data: