services:
  backend:
    volumes:
      - ./backend/app:/app/app
      - ./backend/tests:/app/tests
      - ./backend/.env:/app/.env

  frontend:
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/.env:/app/.env