version: '3.8'

services:
  backend:
    image: registry.cstrube.de/etiketten-app/backend:stage
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - etiketten-netzwerk
    environment:
      - DOCKER_REGISTRY_URL=registry.cstrube.de
      - DOCKER_REGISTRY_USERNAME=${DOCKER_REGISTRY_USERNAME}
      - DOCKER_REGISTRY_PASSWORD=${DOCKER_REGISTRY_PASSWORD}
    entrypoint: /bin/sh -c "echo $DOCKER_REGISTRY_PASSWORD | docker login $DOCKER_REGISTRY_URL -u $DOCKER_REGISTRY_USERNAME --password-stdin && docker-compose up"

  frontend:
    image: registry.cstrube.de/etiketten-app/frontend:stage
    env_file:
      - ./frontend/.env
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - etiketten-netzwerk


networks:
  etiketten-netzwerk:
    driver: bridge