version: '3.8'

services:
  backend:
    image: registry.cstrube.de/etiketten-app/backend:main
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - etiketten-netzwerk

  frontend:
    image: registry.cstrube.de/etiketten-app/frontend:main
    env_file:
      - ./frontend/.env
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - etiketten-netzwerk

networks:
  etiketten-netzwerk:
    driver: bridge