services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend/app:/app/app
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend